version: '3'

services:
  mybackend:
    image: instaclone-backend-img
    container_name: my-backend
    ports:
      - "8080:8080"
    volumes:
      - /c/Users/Ansuman Samal/Documents/insta-bucket:/app/filebucket  
    networks:
      - web_dev_bridge


  mysql:
    image: testsql-web-img
    container_name: testsql-web 
    ports:
      - "3306:3306"  # Map MySQL port
    networks:
      - web_dev_bridge  # Connect to the custom bridge network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-web
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    networks:
      - web_dev_bridge
networks:
  web_dev_bridge:  # Declare the custom bridge network
