version: '3'

services:
  mybackend:
    image: instaclone-backend-img
    container_name: my-backend
    volumes:
      - /home/ansuman/Documents/docker-buckets/insta-bucket:/app/filebucket  
    networks:
      - web_dev_bridge


  mysql:
    image: testsql-web-img
    container_name: testsql-web 
    ports:
      - "3306:3306"  # Map MySQL port
    networks:
      - web_dev_bridge  # Connect to the custom bridge network

  # frontend:
  #   container_name: my-frontend
  #   build:
  #     context: /home/ansuman/Documents/my-frontend  # Path to your frontend Dockerfile
  #     dockerfile: Dockerfile
  #   networks:
  #     - web_dev_bridge  # Connect to the custom bridge network
  #   ports:
  #     - "3000:3000" 


networks:
  web_dev_bridge:  # Declare the custom bridge network
